---
- name: Installing my basic system utilities
  hosts: localhost
  become: yes

  tasks:

   - name: Create the user Poiipoii with sudo privileges
     ansible.builtin.user:
       name: poiipoii
       state: present
       createhome: true
       groups: wheel
       append: true
       shell: /bin/bash
  
   - name: Full system upgrade with pacman
     community.general.pacman:
       update_cache: true
       upgrade: true
  
   - name: install vim and git
     community.general.pacman:
       name:
         - vim
         - git
       state: present
  
   - name: Install i3 window manager
     community.general.pacman:
       name:
         - i3-wm
         - i3lock
       state: present
    
   - name: Install kitty terminal
     community.general.pacman:
       name:
         - kitty
       state: present
  
   - name: Install obsidian
     community.general.pacman:
       name: obsidian
       state: present

   - name: Install Google Chrome with yay
     become: no
     command: yay -S google-chrome --noconfirm -q
     ignore_errors: yes





    


